name: Manual Release
on:
  workflow_dispatch:
    inputs:
      godot_version:
        description: Godot Version Semver
        default: "4.3"
        required: true
        type: string
      release_name: 
        description: Release tag, ie stable, rc1, dev, ect
        default: stable
        required: true
        type: string

    
jobs:
  determine_version:
    uses: ./.github/workflows/determine-version.yml

  build_image:
    needs: determine_version
    uses: ./.github/workflows/build-image.yml
    with:
      sem_ver: ${{ needs.determine_version.outputs.sem_ver }}
      godot_version: ${{ inputs.godot_version }}
      release_name: ${{ inputs.release_name }}
      release_image: false

  build_projects:
    needs:
      - determine_version
      - build_image
    uses: ./.github/workflows/build-projects.yml
    with:
      sem_ver: ${{ needs.determine_version.outputs.sem_ver }}
      build_image: ${{ needs.build_image.outputs.github_image_name_and_tag }}


  build_image_for_release:
    needs: 
      - determine_version
      - build_projects
    uses: ./.github/workflows/build-image.yml
    with:
      sem_ver: ${{ needs.determine_version.outputs.sem_ver }}
      godot_version: ${{ inputs.godot_version }}
      release_name: ${{ inputs.release_name }}
      release_image: true
    secrets: inherit
